# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3a8f19ee2cc71b27b75ec92d41c11b5804dd17a8d8dfd7cf575e4f1276e8d56cf65221a4fd8bf33a3d870741ff2921501e84fe6f927366f489126df82b5d7b44

test:
  secret_key_base: 99870f445d4b308db3043a475fcbe52d6de03d2fa2ef0b6a5e4318b18931e4cf2bce4a7c2f9a3842e3404b4ec2dd67c07866ca07549c8e2c652a795b38bdc140

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
